name: donetick
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - ./data:/donetick-data
      - ./config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
      # Facultatifs
      - DT_IS_USER_CREATION_DISABLED=true
      - DT_NAME=selfhosted
      - DT_JWT_SECRET=${JWTTOKEN}
      - DT_OAUTH2_CLIENT_ID=${CLIENTID}
      - DT_OAUTH2_CLIENT_SECRET=${CLIENTSECRET}
      - DT_OAUTH2_AUTH_URL=${OAUTHURL}
      - DT_OAUTH2_TOKEN_URL=${OAUTHTOKEN}
      - DT_OAUTH2_USER_INFO_URL=${OAUTHUSERINFO}
      - DT_OAUTH2_REDIRECT_URL=${OAUTHREDURL}
      - DT_OAUTH2_NAME=${OAUTHNAME}

